package com.murattahtaci.abaparchitect.core;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public final class Converter {

    private Converter() {
    }

    public static GenerateResult generate(String text, Format format, GenerateOptions options) throws Exception {
        long start = System.currentTimeMillis();
        GenerateResult result = format == Format.XML
                ? generateXml(text, options)
                : generateJson(text, options);
        result.elapsedMillis = System.currentTimeMillis() - start;
        return result;
    }

    private static GenerateResult generateJson(String text, GenerateOptions options) throws JsonParseException {
        GenerateResult result = new GenerateResult();
        Object json = JsonParser.parse(text);

        AbapTypeGenerator generator = new AbapTypeGenerator(options);
        generator.parseNode(json, options.root == null ? "" : options.root, false);
        result.typeCount = generator.getTypeDefs().size();
        result.types = "* ── ABAP Type Definitions ────────────────────────────────────────────────────\n"
                + "* Generated by ABAP Architect\n\n"
                + String.join("\n\n", generator.getTypeDefs());

        Set<String> uniqueMappings = new LinkedHashSet<>(generator.getMapLines());
        result.mappingCount = uniqueMappings.size();
        StringBuilder mapping = new StringBuilder();
        mapping.append("DATA: lt_map TYPE /ui2/cl_json=>name_mappings.\n\n");
        if (uniqueMappings.isEmpty()) {
            mapping.append("* ").append(options.turkish
                    ? "Alan eşleştirmesi gerekmiyor."
                    : "No name mapping needed.");
        } else {
            mapping.append("lt_map = VALUE #(\n");
            mapping.append(String.join("\n", new ArrayList<>(uniqueMappings)));
            mapping.append("\n).");
        }
        result.mapping = mapping.toString();
        result.template = TemplateGenerator.jsonTemplate(options.turkish);
        return result;
    }

    private static GenerateResult generateXml(String text, GenerateOptions options) throws Exception {
        GenerateResult result = new GenerateResult();
        Document document = XmlSupport.parse(text);
        Element rootElement = document.getDocumentElement();
        String rootName = options.root == null || options.root.isEmpty()
                ? NameUtil.toV(rootElement.getTagName(), options.snakeCase)
                : options.root;

        XmlAbapTypeGenerator generator = new XmlAbapTypeGenerator(options);
        generator.parseElement(rootElement, rootName, false);
        result.typeCount = generator.getTypeDefs().size();
        result.types = "* ── ABAP Type Definitions (from XML) ──────────────────────────────\n"
                + "* Generated by ABAP Architect\n\n"
                + String.join("\n\n", generator.getTypeDefs());

        result.ixml = new IXmlCodeGenerator(options).generate(rootElement, rootName);
        result.simpleTransformation = new SimpleTransformationGenerator(options).generate(rootElement);
        result.template = TemplateGenerator.xmlTemplate(options.turkish);
        return result;
    }

    public static String prettify(String text, Format format) throws Exception {
        if (format == Format.XML) {
            return XmlSupport.prettyPrint(text);
        }
        return JsonWriter.prettyPrint(JsonParser.parse(text));
    }

    public static List<String> parseErrorLines(String text, Format format) {
        List<String> errors = new ArrayList<>();
        try {
            if (format == Format.XML) {
                XmlSupport.parse(text);
            } else {
                JsonParser.parse(text);
            }
        } catch (JsonParseException e) {
            errors.add(e.getMessage());
        } catch (Exception e) {
            if (e instanceof org.xml.sax.SAXParseException) {
                org.xml.sax.SAXParseException sax = (org.xml.sax.SAXParseException) e;
                errors.add(sax.getMessage() + " (satır " + sax.getLineNumber() + ", sütun " + sax.getColumnNumber() + ")");
            } else {
                errors.add(String.valueOf(e.getMessage()));
            }
        }
        return errors;
    }
}
