package com.murattahtaci.abaparchitect.core;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.w3c.dom.Element;

public class IXmlCodeGenerator {

    private final GenerateOptions options;

    public IXmlCodeGenerator(GenerateOptions options) {
        this.options = options;
    }

    public String generate(Element rootElement, String rootName) {
        boolean turkish = options.turkish;
        String structName = options.structPrefix + NameUtil.toV(rootName, options.snakeCase);
        String rootTag = rootElement.getTagName();

        StringBuilder code = new StringBuilder();
        code.append("* ── iXML ").append(turkish ? "Ayrıştırma Kodu" : "Parsing Code")
                .append(" ──────────────────────\n");
        code.append("* Generated by ABAP Architect\n\n");
        code.append("DATA: lo_ixml    TYPE REF TO if_ixml,\n");
        code.append("      lo_doc     TYPE REF TO if_ixml_document,\n");
        code.append("      lo_parser  TYPE REF TO if_ixml_parser,\n");
        code.append("      lo_sf      TYPE REF TO if_ixml_stream_factory,\n");
        code.append("      lo_stream  TYPE REF TO if_ixml_istream.\n\n");
        code.append("lo_ixml   = cl_ixml=>create( ).\n");
        code.append("lo_doc    = lo_ixml->create_document( ).\n");
        code.append("lo_sf     = lo_ixml->create_stream_factory( ).\n");
        code.append("lo_stream = lo_sf->create_istream_string( lv_xml_string ).\n");
        code.append("lo_parser = lo_ixml->create_parser(\n");
        code.append("  stream_factory = lo_sf\n");
        code.append("  istream        = lo_stream\n");
        code.append("  document       = lo_doc ).\n");
        code.append("lo_parser->parse( ).\n\n");
        code.append("* ").append(turkish ? "Root elemana git" : "Navigate to root element").append('\n');
        code.append("DATA(lo_root) = lo_doc->find_from_name( name = '").append(rootTag).append("' ).\n");
        code.append("DATA ls_data TYPE ").append(structName).append(".\n\n");
        code.append(extract(rootElement, "lo_root", "ls_data", 0));
        return code.toString();
    }

    private String extract(Element element, String varName, String structVar, int depth) {
        List<Element> childElements = XmlSupport.childElements(element);
        List<XmlSupport.Attr> attributes = XmlSupport.attributes(element);
        String indent = "  ".repeat(depth);
        StringBuilder code = new StringBuilder();

        if (!attributes.isEmpty()) {
            for (XmlSupport.Attr attr : attributes) {
                String field = NameUtil.toV(attr.name, options.snakeCase);
                String target = options.attrFlat ? field : "ATTRIBUTES-" + field;
                code.append(indent).append(structVar).append('-').append(target)
                        .append(" = ").append(varName)
                        .append("->get_attribute( name = '").append(attr.name).append("' ).\n");
            }
        }

        Map<String, Integer> tagCounts = new LinkedHashMap<>();
        for (Element child : childElements) {
            tagCounts.merge(child.getTagName(), 1, Integer::sum);
        }

        for (Map.Entry<String, Integer> tagEntry : tagCounts.entrySet()) {
            String tagName = tagEntry.getKey();
            Element child = firstWithTag(childElements, tagName);
            if (child == null) {
                continue;
            }
            String field = NameUtil.toV(tagName, options.snakeCase);
            String low = field.toLowerCase(Locale.ROOT);
            boolean isArray = tagEntry.getValue() > 1;
            boolean hasKids = !XmlSupport.childElements(child).isEmpty()
                    || !XmlSupport.attributes(child).isEmpty();

            if (isArray) {
                code.append('\n').append(indent).append("* ")
                        .append(options.turkish ? "Dizi elemanlarını oku" : "Read array items")
                        .append(": ").append(tagName).append('\n');
                code.append(indent).append("DATA(lo_iter_").append(low)
                        .append(") = ").append(varName).append("->get_children( )->create_iterator( ).\n");
                code.append(indent).append("DATA(lo_node_").append(low)
                        .append(") = lo_iter_").append(low).append("->get_next( ).\n");
                code.append(indent).append("WHILE lo_node_").append(low).append(" IS NOT INITIAL.\n");
                code.append(indent).append("  IF lo_node_").append(low)
                        .append("->get_name( ) = '").append(tagName).append("'.\n");
                code.append(indent).append("    DATA ls_").append(low)
                        .append(" LIKE LINE OF ").append(structVar).append('-').append(field).append(".\n");
                code.append(indent).append("    CLEAR ls_").append(low).append(".\n");
                if (hasKids) {
                    code.append(extract(child, "lo_node_" + low, "ls_" + low, depth + 2));
                } else {
                    code.append(indent).append("    ls_").append(low)
                            .append(" = lo_node_").append(low).append("->get_value( ).\n");
                }
                code.append(indent).append("    APPEND ls_").append(low)
                        .append(" TO ").append(structVar).append('-').append(field).append(".\n");
                code.append(indent).append("  ENDIF.\n");
                code.append(indent).append("  lo_node_").append(low)
                        .append(" = lo_iter_").append(low).append("->get_next( ).\n");
                code.append(indent).append("ENDWHILE.\n");
            } else if (hasKids) {
                code.append('\n').append(indent).append("* ")
                        .append(options.turkish ? "İç yapıyı oku" : "Read nested structure")
                        .append(": ").append(tagName).append('\n');
                code.append(indent).append("DATA(lo_").append(low).append(") = ").append(varName)
                        .append("->find_from_name( name = '").append(tagName).append("' ).\n");
                code.append(indent).append("IF lo_").append(low).append(" IS NOT INITIAL.\n");
                code.append(extract(child, "lo_" + low, structVar + "-" + field, depth + 1));
                code.append(indent).append("ENDIF.\n");
            } else {
                code.append(indent).append("DATA(lo_").append(low).append(") = ").append(varName)
                        .append("->find_from_name( name = '").append(tagName).append("' ).\n");
                code.append(indent).append("IF lo_").append(low).append(" IS NOT INITIAL.\n");
                code.append(indent).append("  ").append(structVar).append('-').append(field)
                        .append(" = lo_").append(low).append("->get_value( ).\n");
                code.append(indent).append("ENDIF.\n");
            }
        }
        return code.toString();
    }

    private Element firstWithTag(List<Element> elements, String tagName) {
        for (Element element : elements) {
            if (tagName.equals(element.getTagName())) {
                return element;
            }
        }
        return null;
    }
}
