package com.murattahtaci.abaparchitect.core;

public final class TemplateGenerator {

    private TemplateGenerator() {
    }

    public static String jsonTemplate(boolean turkish) {
        String tr = turkish ? "KOD ŞABLONLARI" : "CODE TEMPLATES";
        return "* ══════════════════════════════════════════════════════════════════════\n"
                + "* MODERN ABAP WEB SERVICE — " + tr + "\n"
                + "* ══════════════════════════════════════════════════════════════════════\n\n"
                + "*─── 1. " + (turkish ? "JSON'ı ABAP'a Dönüştür (Deserialize)" : "Convert JSON to ABAP (Deserialize)") + " ────────────────\n"
                + "/ui2/cl_json=>deserialize(\n"
                + "  EXPORTING\n"
                + "    json             = lv_json_input\n"
                + "    pretty_name      = /ui2/cl_json=>pretty_mode-camel_case\n"
                + "    conversion_exits = abap_true\n"
                + "  CHANGING\n"
                + "    data             = ls_target\n"
                + ").\n\n"
                + "*─── 2. " + (turkish ? "ABAP'ı JSON'a Dönüştür (Serialize)" : "Convert ABAP to JSON (Serialize)") + " ────────────────\n"
                + "DATA(lv_json) = /ui2/cl_json=>serialize(\n"
                + "  EXPORTING\n"
                + "    data           = ls_abap_data\n"
                + "    pretty_name    = /ui2/cl_json=>pretty_mode-camel_case\n"
                + "    compress       = abap_true\n"
                + "    numc_as_string = abap_true\n"
                + ").\n\n"
                + "*─── 3. " + (turkish ? "Özel Alan Eşleştirme ile Serialize" : "Serialize with Custom Name Mapping") + " ─────\n"
                + "DATA(lt_map) = VALUE /ui2/cl_json=>name_mappings(\n"
                + "  ( abap = 'MATNR' json = 'productId' )\n"
                + "  ( abap = 'WERKS' json = 'plantId'   )\n"
                + ").\n"
                + "DATA(lv_json_mapped) = /ui2/cl_json=>serialize(\n"
                + "  EXPORTING\n"
                + "    data          = ls_data\n"
                + "    name_mappings = lt_map\n"
                + ").\n\n"
                + "*─── 4. " + (turkish ? "HTTP İstemci (SM59 Hedefi)" : "HTTP Client (SM59 Destination)") + " ──────────────────────────\n"
                + "DATA: lo_client TYPE REF TO if_http_client.\n"
                + "cl_http_client=>create_by_destination(\n"
                + "  EXPORTING destination = 'Z_MY_API'\n"
                + "  IMPORTING client      = lo_client\n"
                + "  EXCEPTIONS OTHERS     = 1\n"
                + ").\n"
                + "IF sy-subrc <> 0. \" " + (turkish ? "Bağlantı hatası" : "Connection error") + " ENDIF.\n\n"
                + "*─── 5. " + (turkish ? "POST İsteği (Bearer Token)" : "POST Request (Bearer Token)") + " ───────────────────────────\n"
                + "lo_client->request->set_method( if_http_request=>co_request_method_post ).\n"
                + "lo_client->request->set_content_type( 'application/json; charset=utf-8' ).\n"
                + "lo_client->request->set_header_field(\n"
                + "  name  = 'Authorization'\n"
                + "  value = |Bearer { lv_token }|\n"
                + ").\n"
                + "lo_client->request->set_cdata( lv_json ).\n"
                + "lo_client->send( ).\n"
                + "lo_client->receive( ).\n\n"
                + "DATA(lv_response) = lo_client->response->get_cdata( ).\n"
                + "DATA(lv_code)     = lo_client->response->get_status_code( ).\n"
                + "lo_client->close( ).\n\n"
                + "IF lv_code <> 200.\n"
                + "  \" " + (turkish ? "HTTP hatasını işle" : "Handle HTTP error") + "\n"
                + "ENDIF.";
    }

    public static String xmlTemplate(boolean turkish) {
        String tr = turkish ? "KOD ŞABLONLARI" : "CODE TEMPLATES";
        return "* ══════════════════════════════════════════════\n"
                + "* MODERN ABAP WEB SERVICE — XML " + tr + "\n"
                + "* ══════════════════════════════════════════════\n\n"
                + "*─── 1. " + (turkish ? "XML Yanıtını iXML ile Ayrıştır" : "Parse XML Response with iXML") + " ---\n"
                + "DATA: lo_ixml   TYPE REF TO if_ixml,\n"
                + "      lo_doc    TYPE REF TO if_ixml_document,\n"
                + "      lo_parser TYPE REF TO if_ixml_parser.\n\n"
                + "lo_ixml   = cl_ixml=>create( ).\n"
                + "lo_doc    = lo_ixml->create_document( ).\n"
                + "DATA(lo_sf) = lo_ixml->create_stream_factory( ).\n"
                + "DATA(lo_stream) = lo_sf->create_istream_string( lv_xml_response ).\n"
                + "lo_parser = lo_ixml->create_parser(\n"
                + "  stream_factory = lo_sf\n"
                + "  istream        = lo_stream\n"
                + "  document       = lo_doc ).\n"
                + "lo_parser->parse( ).\n\n"
                + "*─── 2. " + (turkish ? "Basit Dönüşüm ile Ayrıştır" : "Parse with Simple Transformation") + " ---\n"
                + "CALL TRANSFORMATION z_my_transform\n"
                + "  SOURCE XML lv_xml_response\n"
                + "  RESULT root = ls_data.\n\n"
                + "*─── 3. " + (turkish ? "ABAP Verisini XML'e Dönüştür" : "Convert ABAP to XML") + " ---\n"
                + "CALL TRANSFORMATION z_my_transform\n"
                + "  SOURCE root = ls_data\n"
                + "  RESULT XML lv_xml_output.\n\n"
                + "*─── 4. " + (turkish ? "HTTP İstemci (SM59 Hedefi)" : "HTTP Client (SM59 Destination)") + " ---\n"
                + "DATA: lo_client TYPE REF TO if_http_client.\n"
                + "cl_http_client=>create_by_destination(\n"
                + "  EXPORTING destination = 'Z_MY_XML_API'\n"
                + "  IMPORTING client      = lo_client\n"
                + "  EXCEPTIONS OTHERS     = 1\n"
                + ").\n"
                + "IF sy-subrc <> 0. \" " + (turkish ? "Bağlantı hatası" : "Connection error") + " ENDIF.\n\n"
                + "*─── 5. " + (turkish ? "POST İsteği (XML, Bearer Token)" : "POST Request (XML, Bearer Token)") + " ---\n"
                + "lo_client->request->set_method( if_http_request=>co_request_method_post ).\n"
                + "lo_client->request->set_content_type( 'text/xml; charset=utf-8' ).\n"
                + "lo_client->request->set_header_field(\n"
                + "  name  = 'Authorization'\n"
                + "  value = |Bearer { lv_token }|\n"
                + ").\n"
                + "lo_client->request->set_cdata( lv_xml_request ).\n"
                + "lo_client->send( ).\n"
                + "lo_client->receive( ).\n\n"
                + "DATA(lv_response) = lo_client->response->get_cdata( ).\n"
                + "DATA(lv_code)     = lo_client->response->get_status_code( ).\n"
                + "lo_client->close( ).\n\n"
                + "IF lv_code <> 200.\n"
                + "  \" " + (turkish ? "HTTP hatasını işle" : "Handle HTTP error") + "\n"
                + "ENDIF.";
    }
}
